//language change zh-cn
// Author: kyon
// Date: 2017-08-11

var rblanguage= {
	login: {
		username:'Username',
		password:'Password',
		code:'Verification Code',
	},
	admin: {
		bankname:'Bank Name',
		account:'Administrator Account',
		phone:'Administrator Phone Number',
		contactname:'Contact Person Name',
		contactphone:'Contact Person Phone Number',
		style:'Style',
		loginaddress:'Login link',
		successmsg:'Added successfully',
		errormsg:'Exception',
		savemsg:'Saved successfully',
		configmsg:'Configured successfully',
		resetpassword:'Reset Password',
		repasstip:'Are you sure you want to reset your password? The password will be sent to bank administrator after being reset',
		resetmsg:'Reset successfully',
		disable:'Disable',
		bankdistip:'Are you sure you want to disable this bank?',
		disablemsg:'Disabled successfully',
		enablemsg:'Enabled successfully',
		email:'Email',
		province:'Province',
		city:'City',
	},
	alipay:{
		signdate:'Registration Date',
		name:'Name',
		birth:'Date of Birth',
		id:'ID Number',
		cantact:'Contact Information',
		residence:'Location of Household Register',
		address:'Residential Address',
		namemsg:'Names can be only letters and Chinese characters',
		idmsg:'Please enter a valid ID number',
		valid:'Please enter a valid',
		listtitle:'Select payment amount',
		stunumber:'Student Id',
		confir:'After it has been removed, you can make payments only by selecting Student ID in the future, are you sure you want to continue?',
		delconfirm:'Are you sure you want to delete the order?',
		begintime:'Start Date',
		endtime:'End Date',
		pay:'Payment',
		otherpaying:"其他用户正在支付。",
		neterror:"Network connection error, please try again later!",
		paysuccess:"支付成功!",
		payfail:"支付失败",
		groupname:'Group Name',
		adminaccount:'Admin Account',
		role:'Role',
	},
	bank:{
		username:'Username',
		editmsg:'Updated successfully',
		repasswordgtip:'Are you sure you want to reset your password? The password will be sent to group administrator after being reset',
		disableadmintip:'Are you sure you want to disable this administrator?',
		deladmintip:'Are you sure you want to delete this administrator?',
		del:'Delete',
		delmsg:'Deleted successfully',
		rolename:'Role Name',
		roleconfig:'Role Based Authority Configuration',
		delgrouptip:'Are you sure you want to disable this group?',
		menuallocation:'Menu Assignment',
	},
	group:{
		businessname:'Merchant Name',
		privatekey:'Private Key',
		scope:'Application Scope',
		disablebusiness:'Are you sure you want to disable this merchant?',
		delschooltip:'Are you sure you want to delete this school?',
		setmsg:'Set successfully',
		schoolname:'School Name',
		adminname:'Administrator Name',
		disableschooltip:'Are you sure you want to disable this school?',
		repasswordtip:'Are you sure you want to reset your password? The password will be sent to school administrator after being reset',
		repasswordmsg:'Password reset successful',
		resetkey:'Reset authorization password',
		resetmsg:'Authorization password reset successful',
		resetkeytip:'Are you sure you want to reset your authorization password? The password will be sent to school administrator after being reset',
	},
	school:{
		lifename:'Alipay Life Account Name',
		paymentway:'Payment Method',
		paymentitem:'Payment',
		payTypeId:'Item Category',
		paymentamount:'Payment Amount',
		paytime:'Payment Start Date',
		paytimeend:'Payment End Date',
		allbusiness:'All Merchant Names',
		disabletollitem:'Disable Charges Collectible',
		distollitemtip:'After it has been disabled, you cannot make any payment, are you sure you want to continue?',
		deltollitem:'Delete charges collectible',
		deltip:'Confirm deletion',
		matip:'?',
		enabled:'Enabled',
		disabled:'Disabled',
		allpayitem:'All Payments',
		userenteramount:'Manual Input Amount',
        itemfeetip:'缴费金额只能输入整数或两位小数',
        moduleerror:'request timeout, please re-import',
        copysuccess:'successfully copied'
	},
	oldpage:{
		entername:'Please enter name',
		gendermsg:'Please select gender',
		birthmsg:'Please select date of birth',
		cantactmsg:'Please enter contact information',
		cantacterror:'Please enter a valid contact information',
		emailerror:'The email address you entered is in an invalid format',
		grademsg:'Please select grade',
		yearmsg:'Please select the school enrollment year',
		classesmsg:'Please select class',
		newstu:'Please select at least one new student',
		neterrormsg:'Network connection error, please try again later!',
		newsuccessmsg:'Added successfully',
		majormsg:'Please select a college or department',
		errortips:'Please do not enter any special characters',
		classesnamemsg:'Please enter a class name',
		selectmajormsg:'Please select your assigned major',
		institutesmsg:'Please enter a college or department name',
		selinstitutesmsg:'Please select a college or department name',
		majornamemsg:'Please enter major name',
		allinstitutesmsg:'All Departments',
		selectinstitutesmsg:'Please select your assigned department！',
		selectgrademsg:'Please select your assigned grade！',
		selectmajor:'Please select your assigned major！',
		neterror:"网络连接出错！",
		editmsg:'Updated successfully',
		deletemsg:'Deleted successfully',
		classeserrormsg:'Class name cannot be empty！',
		editsuccess:'Updated successfully',
		enterinstitutes:'Please enter a department name',
		majornonemsg:'The major name cannot be empty',
		gradenonemsg:'The grade name cannot be empty',
	}
};

 var defaults = {
 	    isSubmitGo:false, 
        messages: {
            required: 'The %s field is required.',
            matches: 'The %s field does not match the %s field.',
            "default": 'The %s field is still set to default, please change.',
            valid_email: 'The %s field must contain a valid email address.',
            valid_emails: 'The %s field must contain all valid email addresses.',
            min_length: 'The %s field must be at least %s characters in length.',
            max_length: 'The %s field must not exceed %s characters in length.',
            exact_length: 'The %s field must be exactly %s characters in length.',
            greater_than: 'The %s field must contain a number greater than %s.',
            less_than: 'The %s field must contain a number less than %s.',
            alpha: 'The %s field must only contain alphabetical characters.',
            alpha_numeric: 'The %s field must only contain alpha-numeric characters.',
            alpha_dash: 'The %s field must only contain alpha-numeric characters, underscores, and dashes.',
            numeric: 'The %s field must contain only numbers.',
            integer: 'The %s field must contain an integer.',
            decimal: 'The %s field must contain a decimal number.',
            is_natural: 'The %s field must contain only positive numbers.',
            is_natural_no_zero: 'The %s field must contain a number greater than zero.',
            valid_ip: 'The %s field must contain a valid IP.',
            valid_base64: 'The %s field must contain a base64 string.',
            valid_credit_card: 'The %s field must contain a valid credit card number.',
            is_file_type: 'The %s field must contain only %s files.',
            valid_url: 'The %s field must contain a valid URL.',
            greater_than_date: 'The %s field must contain a more recent date than %s.',
            less_than_date: 'The %s field must contain an older date than %s.',
            greater_than_or_equal_date: 'The %s field must contain a date that\'s at least as recent as %s.',
            less_than_or_equal_date: 'The %s field must contain a date that\'s %s or older.',
            valid_phone:'The %s field must contain a valid Phone No.',
            no_space:'The %s field can not contain space'
        },
        callback: function(errors) {

        }
    };
